services:
  airflow:
    build: .
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session  
      - AIRFLOW__WEBSERVER__RBAC=True  
      - AIRFLOW__WEBSERVER__WEB_SERVER_USERNAME=${AIRFLOW_USERNAME} 
      - AIRFLOW__WEBSERVER__WEB_SERVER_PASSWORD=${AIRFLOW_PASSWORD} 
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./mlruns:/opt/airflow/mlruns
      - ./src/config:/opt/airflow/config
      - ./docker/setup_airflow.sh:/opt/airflow/setup_airflow.sh
      - ./airflow/logs:/var/log/airflow
    networks:
      - app_network
    command: ["bash", "-c", "bash /opt/airflow/setup_airflow.sh"]

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - airflow
    networks:
      - app_network
    command: ["uvicorn", "src.serve.main:app", "--host", "0.0.0.0", "--port", "8000"]

  mlflow:
    image: bitnamicharts/mlflow
    ports:
      - "5001:5001"
    networks:
      - app_network
    environment:
      - MLFLOW_SERVER_FILE_STORE=/app/mlruns
      - MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT=/app/mlruns
    volumes:
      - ./mlruns:/app/mlruns

networks:
  app_network:
    driver: bridge
