name: Airflow DAG Backfill Test

on:
  push:
    paths:
      - 'airflow/dags/**'
      - '.github/workflows/backfill.yml'
  workflow_dispatch:

jobs:
  backfill-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Copy CI environment file
        run: cp .github/workflows/.env.ci .env

      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d
          sleep 30

      - name: Trigger DAG backfill
        run: |
          docker compose exec airflow airflow dags backfill -s $(date +%F) ml_pipeline_dag