name: Docker Build

on:
  push:
    branches: [main]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (optional)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all services with Docker Compose
        run: |
          docker compose build

      - name: Run containers
        run: |
          docker compose up -d
          sleep 30  # Wait for containers to initialize

      - name: Check FastAPI health
        run: |
          curl --fail http://localhost:8000/health

      - name: Check MLflow UI health
        run: |
          curl --fail http://localhost:5001

      - name: Check Airflow UI health
        run: |
          curl --fail http://localhost:8080/health || echo "Airflow health endpoint may need login"
